<?php

include_once DRUPAL_ROOT . '/' . drupal_get_path('module', 'cloudinary') . '/cloudinary.field.inc';
include_once DRUPAL_ROOT . '/' . drupal_get_path('module', 'cloudinary') . '/cloudinary.api.batch.inc';
include_once DRUPAL_ROOT . '/' . drupal_get_path('module', 'cloudinary') . '/cloudinary.entity.inc';
include_once DRUPAL_ROOT . '/' . drupal_get_path('module', 'cloudinary') . '/cloudinary.views.default.inc';

/**
 * Implements hook_libraries_info().
 *
 * For defining external libraries.
 */
function cloudinary_libraries_info() {
  $libraries['cloudinary'] = array(
    'name' => 'Cloudinary',
    'vendor url' => 'http://cloudinary.com/documentation/php_integration',
    'download url' => 'https://github.com/cloudinary/cloudinary_php/tarball/master',
    'files' => array(
      'php' => array('src/Cloudinary.php', 'src/Uploader.php', 'src/Api.php'),
    ),
    'version arguments' => array(
      'file' => 'composer.json',
      'pattern' => '@(?<=version": ")([0-9\.a-z]+)@',
    ),
  );

  return $libraries;
}

/**
 * Implements hook_help().
 */
function cloudinary_help($path, $arg) {
  switch ($path) {
    case 'admin/help#cloudinary':
      $output = '';
      $output .= '<h3>' . t('Cloudinary - Installation and Tips') . '</h3>';
      $output .= '<p>' . t('The Cloudinary module allows you to automatically publish images to Cloudinary through image fields. The returned results can have image styles applied.') . '</p>';
      $output .= '<h4>' . t('Prerequisites') . '</h4>';
      $output .= '<ol>';
      $output .= '<li>' . t('At least version 7.x-2.0-alpha3 of the media module required, found <a href="https://www.drupal.org/node/2120855">here</a>.') . '</li>';
      $output .= '<li>' . t('File entity module version 2 required.') . '</li>';
      $output .= '</ol>';
      $output .= '<h4>' . t('Installation') . '</h4>';
      $output .= '<ol>';
      $output .= '<li>' . t('Enable all required contributed modules.') . '</li>';
      $output .= '<li>' . t('Enable the Cloudinary module.') . '</li>';
      $output .= '<li>' . t('On the <a href="/admin/config/media/cloudinary">configuration page</a>, enter all information. This can be found on your Cloudinary dashboard.') . '</li>';
      $output .= '<li>' . t('Next, create a <a href="/admin/config/media/image-styles/add">new image style</a> and give it the effect "Cloudinary"') . '</li>';
      $output .= '<li>' . t('Create a new "Image" field or edit an existing field and set its display to type "Cloudinary Image". In the advanced settings, set the image style to the new style created in step 4.') . '</li>';
      $output .= '</ol>';
      $output .= '<h4>' . t('Additional') . '</h4>';
      $output .= '<ol>';
      $output .= '<li>' . t('If you are uploading JPEGs, make sure to enable the JPEGmini add on in your Cloudinary account. This can be found in "Add-Ons."') . '</li>';
      $output .= '<li>' . t('Drupal will create a "Transformation" for each image style that uses Cloudinary.') . '</li>';
      $output .= '</ol>';
      return $output;
  }
}

/**
 * Implements hook_menu().
 *
 * Defines a menu for Cloudinary settings.
 */
function cloudinary_menu() {
  $items = array();

  $items['cloudinary/create'] = array(
    'page callback' => '_cloudinary_import_media',
    'access arguments' => array('import cloudinary media'),
    'type' => MENU_LOCAL_TASK,
  );

  $items['admin/config/media/cloudinary'] = array(
    'title' => 'Cloudinary management',
    'description' => 'Configure Cloudinary',
    'page callback' => 'cloudinary_settings_page',
    'access arguments' => array('administer cloudinary'),
    'file' => 'cloudinary.admin.inc',
  );
  return $items;
}

function cloudinary_settings_page() {

  $items = array(
    'cloudinary_settings_form' => drupal_get_form('cloudinary_settings_form'),
    'cloudinary_site_prefix_form' => drupal_get_form('cloudinary_site_prefix_form'),
    'cloudinary_context_mapping_settings_form' => drupal_get_form('cloudinary_context_mapping_settings_form'),
    'cloudinary_folder_settings_form' => drupal_get_form('cloudinary_folder_settings_form'),
    'cloudinary_batch_processing_form' => drupal_get_form('cloudinary_batch_processing_form'),
  );

  return $items;
}

/**
 * Implements hook_permission().
 *
 * Defines a single new permission - _administer cloudinary which determines if
 * you can get to the settings page.
 *
 * @return array
 */
function cloudinary_permission() {
  return array(
    'administer cloudinary' => array(
      'title' => t('Administer Cloudinary'),
      'description' => t('Perform administration tasks for Cloudinary.'),
    ),
    'import cloudinary media' => array(
      'title' => t('Import media files from Cloudinary'),
      'description' => t('Cloudinary file importer'),
    ),
  );
}

/**
 * Implements hook_entity_presave().
 *
 * If the entity being saved is a file, upload to Cloudinary.
 * Then reconstruct the uri to use the form cloudinary://id/[cloudinary-id]/ext/[original-file-extension]/original/[original-uri]
 * The file is still saved in Drupal as usual.
 */
function cloudinary_entity_presave($entity, $type) {
  if ($type == 'file' && $entity->type == 'image' && $entity->status == FILE_STATUS_PERMANENT) {
    _cloudinary_save_file_image_to_cloudinary_and_update_entity($entity);
  }
}

function _cloudinary_save_file_image_to_cloudinary_and_update_entity($entity) {

  $scheme = file_uri_scheme($entity->uri);
  if ($scheme == 'cloudinary') {
    return;
  }

  $entity_metadata_wrapper = entity_metadata_wrapper('file', $entity);
  $entity_property_info = $entity_metadata_wrapper->getPropertyInfo();

  $context_mapping = variable_get('cloudinary_field_mappings', array(
    "field_file_image_alt_text" => "alt",
    "field_file_image_title_text" => "caption"
  ));

  $prefix = variable_get('cloudinary_site_prefix', '');

  $context = array();

  // Use mapping details to extract contextural information
  foreach ($context_mapping as $field_id => $cloudinary_context_id) {
    if (!empty($entity_property_info[$field_id]['type']) && $entity_property_info[$field_id]['type'] == 'text') {
      $context[$cloudinary_context_id] = $entity_metadata_wrapper->{$field_id}->value();
    }
    else {
      if (!empty($entity_property_info[$field_id]['type']) && $entity_property_info[$field_id]['type'] == 'taxonomy_term') {
        $context[$cloudinary_context_id] = $entity_metadata_wrapper->{$field_id}->value()->name;
      }
    }
  }

  // Use folder field machine name to extract folder information, types support : text and taxonomy_term
  $folder_field_id = variable_get('cloudinary_folder', '');
  if (strlen($folder_field_id) > 0) {
    if (!empty($entity_property_info[$folder_field_id]['type']) && $entity_property_info[$folder_field_id]['type'] == 'text') {
      $folder = $entity_metadata_wrapper->{$folder_field_id}->value();
    }
    else {
      if (!empty($entity_property_info[$folder_field_id]['type']) && $entity_property_info[$folder_field_id]['type'] == 'taxonomy_term') {
        $folder = $entity_metadata_wrapper->{$folder_field_id}->value()->name;
      }
    }
  }
  else {
    $folder = '';
  }

  // Need to resolve uri before passing it to cloudinary to process
  $entity->uri = _cloudinary_file_upload($entity->uri, $context, $prefix, $folder);
  $entity->destination = $entity->uri;
}

/**
 * Internal function to remove the file extension.
 *
 * @param $filename
 * @return string
 */
function _cloudinary_strip_extension($filename) {
  $pieces = explode('.', $filename);
  unset($pieces[count($pieces) - 1]);
  $new_filename = implode('.', $pieces);
  return $new_filename;
}

/**
 * Initialise Cloudinary connection.
 * Gets the API keys from settings and configures the Cloudinary class.
 */
function _cloudinary_initialize() {
  libraries_load('cloudinary');

  $initialized = &drupal_static('cloudinary_initialised', FALSE);
  if ($initialized) {
    return;
  }

  $api_env = variable_get('cloudinary_env_var', '');

  $prefix = 'CLOUDINARY_URL=';
  if (substr($api_env, 0, strlen($prefix)) == $prefix) {
    $api_env = substr($api_env, strlen($prefix));
  }

  if (_cloudinary_check_connection()) {
    Cloudinary::config_from_url($api_env);

    // Set the global flag for cdn subdomain if applicable.
    if (variable_get('cloudinary_cdn_subdomain', '')) {
      \Cloudinary::config(array("cdn_subdomain" => TRUE));
    }

    $initialized = TRUE;
  }
}

function _cloudinary_extract_uri_elements($uri) {

  // Retrieve normal image url
  $url_parameters = drupal_parse_url($uri);
  $path = $url_parameters['path'];

  // Retrieve the scheme if possible
  $url_parameters['scheme'] = file_uri_scheme($path);

  // If available, strip it off our path
  if (strlen($url_parameters['scheme']) > 0) {
    $path = substr($path, strlen($url_parameters['scheme']) + 3);
  }
  $url_parameters['path_pieces'] = explode('/', $path);

  // Extract final piece so that we can extract file extension
  $final_path_piece = $url_parameters['path_pieces'][count($url_parameters['path_pieces']) - 1];
  $cloudinary_id = _cloudinary_strip_extension($final_path_piece);

  $url_parameters['extension'] = (strlen($final_path_piece) - strlen($cloudinary_id)) > 1 ? substr($final_path_piece, strlen($cloudinary_id) + 1) : 'png';
  $url_parameters['path_pieces'][count($url_parameters['path_pieces']) - 1] = $cloudinary_id;

  return $url_parameters;
}

/**
 * Wrapper function around the Cloudinary class which uploads the image.
 * @param $image
 * @param $id
 */
function _cloudinary_file_upload($image_uri, $context = array(), $prefix = '', $folder = '') {
  libraries_load('cloudinary');
  _cloudinary_initialize();

  $file_real_path = drupal_realpath($image_uri);

  $public_id_components = array();

  // This does not seem to work at the moment
  if (strlen($prefix) > 0) {
    $public_id_components[] = $prefix;
  }
  if (strlen($folder) > 0) {
    $public_id_components[] = $folder;
  }

  $generated_folder = implode('/', $public_id_components);

  $options = array(
    "folder" => $generated_folder,
    "use_filename" => TRUE,
  );

  // Add additional parameters where required
  if (count($context) > 0) {
    $options['context'] = $context;
  }

  $browsable_result = \Cloudinary\Uploader::upload($file_real_path, $options);

  $extension = $browsable_result['format'];

  // Caveat - when uploading using a folder, the folder will automatically be appended to the beginning of the id on the cloudinary side
  $cloudinary_uri = sprintf('cloudinary://id/%s/ext/%s/original/%s', urlencode($browsable_result['public_id']), urlencode($extension), urlencode($image_uri));

  return $cloudinary_uri;
}

/**
 * Implements hook_image_effect_info().
 *
 * Define a new image effect type that will appear in the image effects dropdown.
 */
function cloudinary_image_effect_info() {
  $effects = array();

  $effects['cloudinary_crop'] = array(
    'label' => t('Cloudinary'),
    'help' => t('Applies cloudinary effects'),
    'effect callback' => 'cloudinary_empty_effect',
    'dimensions passthrough' => TRUE,
    'summary theme' => 'cloudinary_crop_summary',
    'form callback' => 'cloudinary_crop_form',
  );

  return $effects;
}

/**
 * Settings form for the Cloudinary image effect.
 * Includes all of the parameters available to manipulate an image in Cloudinary.
 * @param $data
 * @return mixed
 */
function cloudinary_crop_form($data) {
  $form['crop'] = array(
    '#type' => 'select',
    '#title' => t('Crop Type'),
    '#options' => array(
      'crop' => 'crop',
      'fill' => 'fill',
      'lfill' => 'lfill',
      'scale' => 'scale',
      'fit' => 'fit',
      'limit' => 'limit',
      'pad' => 'pad',
      'lpad' => 'lpad',
      'thumb' => 'thumb',
    ),
    '#default_value' => isset($data['crop']) ? $data['crop'] : 'scale',
  );

  $form['width'] = array(
    '#type' => 'textfield',
    '#title' => t('Width (pixels or percentage, such as 0.1)'),
    '#default_value' => isset($data['width']) ? $data['width'] : '1.0',
    '#size' => 10,
  );
  $form['height'] = array(
    '#type' => 'textfield',
    '#title' => t('Height (pixels or percentage, such as 0.1)'),
    '#default_value' => isset($data['height']) ? $data['height'] : '1.0',
    '#size' => 10,
  );

  $form['gravity'] = array(
    '#type' => 'select',
    '#title' => t('Gravity'),
    '#default_value' => isset($data['gravity']) ? $data['gravity'] : '',
    '#options' => array(
      '' => '',
      'center' => 'center',
      'north_west' => 'north_west',
      'north' => 'north',
      'north_east' => 'north_east',
      'east' => 'east',
      'south_east' => 'south_east',
      'south' => 'south',
      'south_west' => 'south_west',
      'west' => 'west',
      'xy_center' => 'xy_center',
      'face' => 'face',
      'face:center' => 'face:center',
      'face (thumb)' => 'face (thumb)',
      'faces' => 'faces',
      'faces:center' => 'faces:center',
    ),
  );

  $form['x'] = array(
    '#type' => 'textfield',
    '#title' => t('X'),
    '#default_value' => isset($data['x']) ? $data['x'] : '',
    '#size' => 10,
  );

  $form['y'] = array(
    '#type' => 'textfield',
    '#title' => t('Y'),
    '#default_value' => isset($data['y']) ? $data['y'] : '',
    '#size' => 10,
  );

  $form['radius'] = array(
    '#type' => 'textfield',
    '#title' => t('Radius (rounded corners radius in px, or max)'),
    '#default_value' => isset($data['radius']) ? $data['radius'] : '',
    '#size' => 10,
  );

  $form['effect'] = array(
    '#type' => 'select',
    '#title' => t('Effect'),
    '#options' => array(
      '' => '',
      'grayscale' => 'grayscale',
      'blackwhite' => 'blackwhite',
      'oil_paint' => 'oil paint',
      'negate' => 'negate',
      'vignette' => 'vignette',
      'sepia' => 'sepia',
      'sepia:50' => 'sepia:50',
      'brightness:60' => 'brightness:60',
      'brightness:-40' => 'brightness:-40',
      'auto_brightness' => 'auto_brightness',
      'fill_light' => 'fill_light',
      'saturation:70' => 'saturation:70',
      'saturation:-50' => 'saturation:-50',
      'pixelate' => 'pixelate',
      'pixelate:3' => 'pixelate:3',
      'pixelate_region' => 'pixelate_region',
      'pixelate_region:20' => 'pixelate_region:20',
      'pixelate_faces' => 'pixelate_faces',
      'pixelate_faces:3' => 'pixelate_faces:3',
      'gradient_fade' => 'gradient_fade',
      'blur' => 'blur',
      'blur:300' => 'blur:300',
      'blur_region' => 'blur_region',
      'blur_faces' => 'blur_faces',
      'sharpen' => 'sharpen',
      'sharpen:400' => 'sharpen:400',
      'unsharp_mask' => 'unsharp_mask',
      'unsharp_mask:400' => 'unsharp_mask:400',
      'contrast:90' => 'contrast:90',
      'contrast:-70' => 'contrast:-70',
      'auto_contrast' => 'auto_contrast',
      'vibrance' => 'vibrance',
      'vibrance:70' => 'vibrance:70',
      'red:50' => 'red:50',
      'green:50' => 'green:50',
      'blue:90' => 'blue:90',
      'auto_color' => 'auto_color',
      'improve' => 'improve',
      'screen' => 'screen',
      'multiply' => 'multiply',
      'make_transparent' => 'make_transparent',
      'trim' => 'trim',
    ),
    '#default_value' => isset($data['effect']) ? $data['effect'] : '',
  );

  $form['quality'] = array(
    '#type' => 'select',
    '#title' => t('Quality'),
    '#options' => drupal_map_assoc(array(
      '',
      10,
      20,
      30,
      40,
      50,
      60,
      70,
      80,
      90,
      100
    )),
    '#default_value' => isset($data['quality']) ? $data['quality'] : '80',
  );

  $form['fetch_format'] = array(
    '#type' => 'select',
    '#title' => t('Fetch format'),
    '#default_value' => isset($data['fetch_format']) ? $data['fetch_format'] : FALSE,
    '#description' => t("Enable support for dynamic delivery of WebP images."),
    '#options' => array(
      '' => '',
      'auto' => 'auto',
    )
  );

  return $form;
}

function cloudinary_empty_effect(&$image, $data) {
  // Does nothing, this is a template effect
  return TRUE;
}

/**
 * Theme function for Cloudinary effect explaining to the developer which effects will be applied.
 * @param $variables
 * @return null|string
 */
function theme_cloudinary_crop_summary($variables) {
  return t('Image will have cloudinary effects applied, using crop : @crop, to the size of @widthx@height, using effect @effect with quality @quality', array(
    '@crop' => $variables['data']['crop'],
    '@width' => $variables['data']['width'],
    '@height' => $variables['data']['height'],
    '@effect' => $variables['data']['effect'],
    '@quality' => $variables['data']['quality'],
  ));
}

/**
 * Implements hook_theme().
 */
function cloudinary_theme() {
  return array(
    'cloudinary_crop_summary' => array(
      'variables' => array('data' => NULL),
    ),
    'image_formatter_cloudinary' => array(
      'variables' => array(
        'item' => NULL,
        'path' => NULL,
        'image_style' => NULL,
        'image_rendered_as_src' => FALSE,
      ),
    ),
    'image_style_cloudinary' => array(
      'variables' => array(
        'image_style' => NULL
      ),
    ),
    'image_cloudinary' => array(
      'variables' => array('transformations' => array()),
    ),
    'image_style_src_cloudinary' => array(
      'variables' => array(
        'image_style' => NULL
      ),
    ),
    'image_src_cloudinary' => array(
      'variables' => array('transformations' => array()),
    ),
  );
}

/**
 * Implements hook_stream_wrappers().
 */
function cloudinary_stream_wrappers() {
  return array(
    'cloudinary' => array(
      'name' => t('Cloudinary hosted images'),
      'class' => 'MediaCloudinaryStreamWrapper',
      'description' => t('Images hosted on Cloudinary'),
      'type' => STREAM_WRAPPERS_READ_VISIBLE,
    ),
  );
}

function cloudinary_media_format_form_prepare_alter(&$form, &$form_state, $media) {
  $settings = array('autosubmit' => ($media->type == "image"));
  drupal_add_js(array('media_format_form' => $settings), 'setting');
}

function cloudinary_ctools_plugin_api($owner, $api) {
  static $api_versions = array(
    'file_entity' => array(
      'file_default_displays' => 1,
    ),
  );
  if (isset($api_versions[$owner][$api])) {
    return array('version' => $api_versions[$owner][$api]);
  }
}

/**
 * Implements hook_file_default_displays().
 */
function cloudinary_file_default_displays() {
  $default_displays = array();

  // Default settings for displaying a video preview image. We enable preview
  // images even for view modes that also play video, for use inside a running
  // WYSIWYG editor. The higher weight ensures that the video display is used
  // where possible.
  $default_image_styles = array(
    'media_preview' => 'square_thumbnail',
    'media_large' => 'large',
    'media_original' => ''
  );
  foreach ($default_image_styles as $view_mode => $image_style) {
    $display_name = 'image__' . $view_mode . '__cloudinary_image';
    $default_displays[$display_name] = (object) array(
      'api_version' => 1,
      'name' => $display_name,
      'status' => 1,
      'weight' => 2,
      'settings' => array('image_style' => $image_style),
    );
  }
  return $default_displays;
}

/**
 * Implements hook_file_mimetype_mapping_alter().
 *
 * Register the image/cloudinary mimetype.
 */
function cloudinary_file_mimetype_mapping_alter(&$mapping) {
  $mapping['mimetypes'][] = 'image/cloudinary';
}

/**
 * Returns the URL for a cloudinary image given a style and filename.
 *
 * @param $style_name
 *   The name of the style to be used with this image.
 * @param $filename
 *   The filename of the image.
 *
 * @return
 *   The absolute URL where a style image can be downloaded.
 */
function cloudinary_style_url($style_name, $filename) {
  $variables = array();

  $style = image_style_load($style_name);

  $scheme = file_uri_scheme($filename);
  if ($scheme == 'cloudinary') {
    $wrapper = file_stream_wrapper_get_instance_by_uri($filename);
    $properties = $wrapper->get_parameters();

    $variables['cloudinary_id'] = $properties['id'];
    $variables['extension'] = $properties['ext'];

    $transformations = array();
    if (is_array($style) && array_key_exists('effects', $style)) {
      foreach ($style['effects'] as $effect) {
        foreach ($effect['data'] as $key => $value) {
          if ($value == '') {
            unset($effect['data'][$key]);
          }
        }
        $transformations[] = $effect['data'];
      }
    }
    $variables['transformations'] = $transformations;
    return theme('image_src_cloudinary', $variables);
  }

  return image_style_url($style, $filename);
}

/**
 * Implements hook_views_api().
 */
function cloudinary_views_api() {
  return array(
    'api' => 3,
    'path' => drupal_get_path('module', 'cloudinary'),
  );
}

/**
 * Implements hook_media_browser_plugin_info().
 *
 * Commented out for release versions, active in dev versions. To enable the
 * YouTube media browser tab, uncomment this function.
 */
function cloudinary_media_browser_plugin_info() {

  $info = array();

  // Add a plugin for each View display using the 'MediaCloudinaryBrowserDisplayPlugin' display type.
  $view_weight = 10;
  foreach (views_get_enabled_views() as $view) {
    foreach ($view->display as $display) {
      if ($display->display_plugin == 'MediaCloudinaryBrowserDisplayPlugin') {
        $title = $display->display_title;
        if (!empty($display->display_options['title'])) {
          $title = $display->display_options['title'];
        }
        $info["{$view->name}--{$display->id}"] = array(
          'title' => $title,
          // @TODO make this configurable.
          'weight' => $view_weight++,
          'class' => 'MediaCloudinaryBrowserView',
          'view_name' => $view->name,
          'view_display_id' => $display->id,
        );
      }
    }
  }

  return $info;
}

/**
 * Implements hook_entity_info().
 */
function cloudinary_entity_info() {
  $return = array(
    'cloudinary_admin_api' => array(
      'label' => t('Cloudinary Admin API Entity'),
      'controller class' => 'CloudinaryAdminAPIEntityController',
      'entity keys' => array(
        'id' => 'public_id',
      ),
      'module' => 'cloudinary',
    )
  );
  return $return;
}

/**
 * Implements hook_entity_property_info().
 */
function cloudinary_entity_property_info() {

  $info['cloudinary_admin_api']['properties'] = array(
    'public_id' => array(
      'label' => t('Public ID'),
      'type' => 'text',
    ),
    'format' => array(
      'label' => t('Format'),
      'type' => 'text',
    ),
    'version' => array(
      'label' => t('Version'),
      'type' => 'integer',
    ),
    'resource_type' => array(
      'label' => t('Resource Type'),
      'type' => 'text',
    ),
    'type' => array(
      'label' => t('Type'),
      'type' => 'text',
    ),
    'created_at' => array(
      'label' => t('Created at'),
      'type' => 'date',
    ),
    'bytes' => array(
      'label' => t('Bytes'),
      'type' => 'integer',
    ),
    'width' => array(
      'label' => t('Width'),
      'type' => 'integer',
    ),
    'height' => array(
      'label' => t('Height'),
      'type' => 'integer',
    ),
    'preview' => array(
      'label' => t('Preview'),
      'type' => 'text',
    ),
  );

  $cloudinary_field_mappings = variable_get('cloudinary_field_mappings', array());
  foreach ($cloudinary_field_mappings as $field => $mapping) {
    $info['cloudinary_admin_api']['properties']['cloudinary_context_' . $mapping] = array(
      'label' => t('Cloudinary Context - ' . $mapping),
      'type' => 'text',
    );
  }

  return $info;
}

function _cloudinary_import_file_entity_from_cloudinary_public_id($cloudinary_id) {
  libraries_load('cloudinary');
  _cloudinary_initialize();

  $api = new \Cloudinary\Api();
  $image_resource = $api->resource(urlencode($cloudinary_id), array('image_metadata' => TRUE));
  $image_resource_array = get_object_vars($image_resource);

  $extension = $image_resource_array['format'];

  $uri = MediaCloudinaryStreamWrapper::encodeURI($cloudinary_id, $extension);
  $file_to_be_saved = file_uri_to_object($uri);

  // Attach preliminary data
  $file_to_be_saved->metadata = array(
    'width' => $image_resource_array['width'],
    'height' => $image_resource_array['height'],
  );

  if (!empty($image_resource_array['context']['custom']['caption'])) {
    $file_to_be_saved->filename = $image_resource_array['context']['custom']['caption'];
  }
  else {
    $file_to_be_saved->filename = $cloudinary_id;
  }

  file_save($file_to_be_saved);

  $fid = $file_to_be_saved->fid;
  $file_loaded = file_load($fid);
  $file_entity_metadata_wrapper = entity_metadata_wrapper('file', $file_loaded);
  $file_entity_metadata_wrapper_property_info = $file_entity_metadata_wrapper->getPropertyInfo();

  $context_mapping = variable_get('cloudinary_field_mappings', array(
    "field_file_image_alt_text" => "alt",
    "field_file_image_title_text" => "caption"
  ));
  $context_mapping_row_data = array();
  foreach ($context_mapping as $field_id => $cloudinary_context_id) {
    if (!empty($image_resource_array['context']['custom'][$cloudinary_context_id])) {

      switch ($file_entity_metadata_wrapper_property_info[$field_id]['type']) {
        case 'taxonomy_term' :
          $vocabulary_identifier = $file_entity_metadata_wrapper_property_info[$field_id]['bundle'];

          $vocabulary = taxonomy_vocabulary_machine_name_load($vocabulary_identifier);

          $query = new EntityFieldQuery;
          $result = $query
            ->entityCondition('entity_type', 'taxonomy_term')
            ->propertyCondition('name', $image_resource_array['context']['custom'][$cloudinary_context_id])
            ->propertyCondition('vid', 1)
            ->execute();

          $tid = -1;
          if (!empty($result['taxonomy_term'])) {
            $first_term = reset($result['taxonomy_term']);
            $tid = $first_term->tid;
          }

          if (-1 === $tid) {
            // Need to create a new taxonomy term and store the tid
            $term = new stdClass();
            $term->name = $image_resource_array['context']['custom'][$cloudinary_context_id];
            $term->vid = $vocabulary->vid;
            taxonomy_term_save($term);
            $tid = $term->tid;
          }

          $file_entity_metadata_wrapper->$field_id->set($tid);
          break;

        case 'text' :
          $file_entity_metadata_wrapper->$field_id->set($image_resource_array['context']['custom'][$cloudinary_context_id]);
          break;
      }
    }
  }

  $file_entity_metadata_wrapper->save();

  return $file_loaded;
}

/**
 * JSON Callback for importing a piece of media into the site
 * The USER requires 'import cloudinary media' access to use it
 */
function _cloudinary_import_media() {
  $response = new stdClass();

  // Retrieve public ID
  if (empty($_POST['data'])) {
    $response->data = NULL;
    $response->error = 1;
    $response->error_message = "No data supplied";
    drupal_json_output($response);
    drupal_exit();
    return;
  }

  try {
    // TODO: Is this secure?
    $remote_json = $_POST['data'];
    $data = json_decode($remote_json);

    $variables = get_object_vars($data);
  } catch (Exception $e) {
    $response->data = NULL;
    $response->error = 2;
    $response->error_message = $e->getMessage();
    drupal_json_output($response);
    drupal_exit();
    return;
  }

  // Retrieve public ID
  if (empty($variables['cloudinary_public_id'])) {
    $response->data = NULL;
    $response->error = 3;
    $response->error_message = "No Cloudinary Public ID supplied";
    drupal_json_output($response);
    drupal_exit();
    return;
  }

  $public_id = $variables['cloudinary_public_id'];

  try {
    $new_imported_entity = _cloudinary_import_file_entity_from_cloudinary_public_id($public_id);
  } catch (Exception $e) {
    $response->data = NULL;
    $response->error = 4;
    $response->error_message = $e->getMessage();
    drupal_json_output($response);
    drupal_exit();
    return;
  }

  $response->data = $new_imported_entity;
  $response->error = 0;
  $response->error_message = "";

  drupal_json_output($response);
  drupal_exit();
}

/**
 * Checks for valid credentials.
 */
function _cloudinary_check_connection() {
  $valid = FALSE;
  $api_env = variable_get('cloudinary_env_var', '');

  if ($api_env) {
    // Break the environment variable into key/secret/cloud.
    preg_match('#(?<=://)([0-9\.a-z\.A-Z]+)#', $api_env, $match);
    if (isset($match[0])) $key = $match[0];

    preg_match('#(?<=\:)([0-9\.a-z\.A-Z]+)#', $api_env, $match);
    if (isset($match[0])) $secret = $match[0];

    preg_match('#(?<=@)([0-9\.a-z\.A-Z]+)#', $api_env, $match);
    if (isset($match[0])) $cloud = $match[0];

    if (isset($key) && isset($secret) && isset($cloud)) {
      $url = sprintf('https://%s:%s@api.cloudinary.com/v1_1/%s/resources/image', $key, $secret, $cloud);

      // Make a curl request to see if the entered details are vaild.
      $curl = curl_init();
      curl_setopt_array($curl, array(
        CURLOPT_RETURNTRANSFER => 1,
        CURLOPT_URL => $url,
        CURLOPT_SSL_VERIFYPEER => FALSE,
      ));
      // Send the request & save response to $resp
      $resp = curl_exec($curl);
      // Close request to clear up some resources
      curl_close($curl);

      if ($resp) {
        $resp = json_decode($resp);

        if (isset($resp->error)) {
          drupal_set_message(t('Cloudinary Environment Variable is invalid, you can enter it !here. Cloudinary error: "!error".',
            array(
              '!here' => l(t('here'), 'admin/config/media/cloudinary'),
              '!error' => $resp->error->message,
            )
          ), 'error');
        }
        else {
          // There is a response, but contains no error, so credentials are valid.
          $valid = TRUE;
        }
      }
      else {
        drupal_set_message(t('Unable to connect to Cloudinary'), 'error');
      }
    }
  }

  return $valid;
}